{
  "formatVersion": "1.1",
  "component": {
    "group": "persist",
    "module": "persist_plugin",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "persist_plugin-0.1.jar",
          "url": "persist_plugin-0.1.jar",
          "size": 13673,
          "sha512": "0b4ad9075488170a5b03e4dd9150f3c3cd713827a3853fa224db823eba07a8bd4eb065449b037bce02b55b55e806d504b5d0569677a821d443336a06f5180293",
          "sha256": "f7c46a7be9978dc0f9f8f4411ffc6b32efcd62f39c83d132f70894b84979bd75",
          "sha1": "6fd06b3e5137eb3a85c6a2437d20bcac83a055b9",
          "md5": "a8f5f7c69ae82ef16783fbed45bb52c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.5.31-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "persist_plugin-0.1.jar",
          "url": "persist_plugin-0.1.jar",
          "size": 13673,
          "sha512": "0b4ad9075488170a5b03e4dd9150f3c3cd713827a3853fa224db823eba07a8bd4eb065449b037bce02b55b55e806d504b5d0569677a821d443336a06f5180293",
          "sha256": "f7c46a7be9978dc0f9f8f4411ffc6b32efcd62f39c83d132f70894b84979bd75",
          "sha1": "6fd06b3e5137eb3a85c6a2437d20bcac83a055b9",
          "md5": "a8f5f7c69ae82ef16783fbed45bb52c3"
        }
      ]
    }
  ]
}
