{
  "formatVersion": "1.1",
  "component": {
    "group": "persist",
    "module": "persist_plugin",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "persist_plugin-0.1.jar",
          "url": "persist_plugin-0.1.jar",
          "size": 18243,
          "sha512": "ceb28b3ae0b11722ef4175819fecf43c61cc31b2b6d2d71d7939fb7282ad6598bf2a2f6551913a33a7ee08df655d3a58ebd8204586a0f504eb4aae5360c22a00",
          "sha256": "5986db83573939ac0bdd9e3075088610b9c92e9417d0fa3dda361c940a6f2799",
          "sha1": "6fe226965ff2fd11264222300c3b57fe5ba8a822",
          "md5": "367b7bee8bcfe298878e164717a81a8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "1.5.31-1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "persist_plugin-0.1.jar",
          "url": "persist_plugin-0.1.jar",
          "size": 18243,
          "sha512": "ceb28b3ae0b11722ef4175819fecf43c61cc31b2b6d2d71d7939fb7282ad6598bf2a2f6551913a33a7ee08df655d3a58ebd8204586a0f504eb4aae5360c22a00",
          "sha256": "5986db83573939ac0bdd9e3075088610b9c92e9417d0fa3dda361c940a6f2799",
          "sha1": "6fe226965ff2fd11264222300c3b57fe5ba8a822",
          "md5": "367b7bee8bcfe298878e164717a81a8f"
        }
      ]
    }
  ]
}
